### ISSUE TITLE
SPC improvements

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/uatk-admin#1]
### Summary
Some basic improvements to SPC that we need in the short term.

### What needs to be done?
- [ ] User defines start date and end date -> SPC outputs all days incl. lockdown, daily activities for each individual, events (Hadrien + REG)
- [ ] Scotland is available (+ maybe a few LADs in England) (Hadrien + REG)
- [ ] Improvements to the web app (Dustin + REG)

### Who can help?
REG resource is needed

**Comment by HSalat** [comment]
## Urgent

- [ ] **Add missing areas:** (REG + HS)
  - [ ] Scotland (all LADs)
  - [ ] England
     - Known issues (no fix):
         - City of London (E09000001)
        - Isle of Scilly (E06000053)
     - SPENSER currently failing:
         - Dorset entirely unavailable (E06000058 & E06000059)
         - Buckinghamshire incomplete (E06000060)
         - Leicestershire incomplete (E07000135)
         - Suffolk incomplete (E07000244 & E07000245)
         - Somerset incomplete (E07000246)
- [ ] **Finish adding logic for events** (REG; support form HS & DC)
- [ ] **Update 'offline' data curation code** (HS)

## Desirable

- [ ] **Find a way to output day by day information** (REG)
    - Dynamic output vs static population
    - Leave options for the user to customise the content of their output
- [ ] **Compartmentalise outputs** to reduce size of unmanageable areas (London, Manchester, etc) and produce Boroughs sample areas for London (REG)
- [ ] **Add tests / validation** (REG + HS)
- [ ] **Robust assignement of homes to individual buildings** (HS + DC?)
- [ ] **Projection module** for non-census data (HS)

## Long term goals

- [ ] **Build upon SPENSER** to create in-house equivalent
- [ ] **Update QUANT** or replace with in-house modelling from other projects
- [ ] **Generalised version** of the model for easier reproducibility outside UK / light global version

**Comment by HSalat** [comment]
**Resources for PENSER**

Detailed status report from previous REG team (includes links to the 5 OG SPENSER repos and current pipeline):
* https://hackmd.io/e-tDthzOTt6CvZ1CE3XRSA

Missing lads:
* https://github.com/alan-turing-institute/uatk-spc/issues/41#issuecomment-1460083428
* https://hackmd.io/Zwa-l5fKS6uQnPz5npAbLg

For ref, initial conversation:
* https://github.com/alan-turing-institute/dymechh/issues/26#issuecomment-1297209992

**Comment by HSalat** [comment]
**Resources for Events**

I wasn’t able to locate a written up version of this. May need to ask @dabreegster what’s been done already.

Attached are the [old python code](https://github.com/alan-turing-institute/uatk-admin/files/11200023/eventsHandler.py.txt) (meant for [ASPICS](https://github.com/alan-turing-institute/uatk-aspics), only function `findVisitors` is relevant for SPC) and [sample events for testing](https://github.com/alan-turing-institute/uatk-admin/files/11200032/eventDataConcerts.csv) (based on the O2). I will write more doc when it’s decided someone will start working on this.

**Comment by dabreegster** [comment]
There are some notes for events scattered in our Slack DMs. I started https://github.com/alan-turing-institute/uatk-spc/blob/web_events/web/events.js before AIUK, but it doesn't do much yet.

**Comment by gmingas** [comment]
Closing this as it is super-seeded by other issues.
